export const CompStyles = {
  body: {
    width: "100vw",
    backgroundColor: "white",
  },
  button: {
    border: "none",
    backgroundColor: "white",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    width: "78px",
    height: "24px",
  },
  container: {
    width: "90vw",
    height: "72px",
    display: "flex",
    paddingLeft: "120px",
    paddingRight: "120px",
    justifyContent: "space-between",
  },
  box1: {
    width: "300px",
    height: "40px",
    gap: "20px",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  box2: {
    width: "163px",
    height: "40px",
    gap: "24px",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  record: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: "20px",
    backgroundColor: "#0166FF",
    color: "white",
    width: "100px",
    height: "32px",
    border: "none",
  },
  dashboard: {
    weight: "600",
    size: "16px",
    lineHeight: "24px",
    cursor: "pointer",
  },
  recordButton: {
    cursor: "pointer",
    weight: "600",
    size: "16px",
    lineHeight: "24px",
  },
  buttonsDiv: {
    display: "flex",
    gap: "40px",
  },
};
